### ISSUE TITLE
Size of the raw data

### ISSUE THREAD

**Issue by YuanZi1501040205** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#10]
Dear Authors,

The data obtained from the MethaneMapper dataset is not the same size as mentioned in the paper. they only got 90 bands, are they in a specific spectral range or just downsampled from the original 432 channels as mentioned in the paper?

load file:
ang20191025t205201_rdn_v2x1_img_tiles/ang20191025t205201_rdn_v2x1_img_19_0.npy
print(loaded_data.shape)
(256, 256, 90)

Many thanks in advance for helping me understand your work!

**Comment by satish1901** [comment]
Hello 

thank you so much for showing interest in our work. The original data with 432 bands was too big (30TB). So we did not release that. 
The Subset 90 bands are taken from wavelengths range (~2100nm to ~2450nm). These bands contains information where methane gas shows maximum absorption of reflected solar radiations. 
These 90 bands are passed to our "backbone" as named in our architecture diagram. 

To access the all 432 bands, please download from here
link : https://popo.jpl.nasa.gov/avng/


Please let me know if this solves your issues!

**Comment by satish1901** [comment]
Hello 
I am closing this issues if there is no follow up question.

thanks
