### ISSUE TITLE
concentration labels

### ISSUE THREAD

**Issue by nell-byler** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#12]
Hi, appreciate your work on this! Your paper mentions releasing the pixel-level methane concentrations for the dataset, but I can't find the annotations.

I have found the bbox and segmentation polygons for the training data in [annotations_16171819.json](https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/blob/main/methanemapper/data/annotations_16171819/annotations_16171819.json) but there is no equivalent for concentration values. This file [methane_signature.txt](https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/blob/main/data/gas_signature/methane_signature.txt) looks like like it could be related to concentration values, but there is only a single file with 425 values, and I have no idea how to connect that back to the existing images/patches.

Thank you!

**Comment by satish1901** [comment]
please send me an email. i will share the concentration labels.
