### ISSUE TITLE
Generate the same data format as you do from raw data

### ISSUE THREAD

**Issue by yaoyuan10475** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#13]
Dear Author:
          I found that there is no 2015 in your public data set. I want to use the 2015 data to generate the same data format as 2016 to 2020 based on the SLF you proposed. I found that there is a train_dataset_generator folder in your public code. Is this the raw data to generate mf_tiles, rgb_tiles and rdata_tiles?

**Comment by satish1901** [comment]
Hello, 
You are right!
train_dataset_generator folder contains all the scripts of generate the training data from raw data. 
It will generate in the same format as data from 2016-2020.
Let me know if it helps

Thanks

**Comment by yaoyuan10475** [comment]
Sorry, I just finished downloading the 2020 data, but I haven't downloaded the 2015 data yet. I'll let you know if I get this far.
I have a new problem now. I followed the steps you provided to train the 2020 data and I cannot start distributed training. My environment is a computer with two RTX3090. 
I set  os.environ["RANK"] = "1" 
os.environ["WORLD_SIZE"] = "2"
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
os.environ["LOCAL_RANK"] = "1"
os.environ["MASTER_ADDR"] = 'localhost'
os.environ["MASTER_PORT"] = '12355'.
But this doesn't work, can you give me some advice on distributed training?
Or can you tell me, only on the 2020 data, the mAP and mIOU results obtained by training your model?

**Comment by yaoyuan10475** [comment]
Sorry, I just finished downloading the 2020 data and haven't started downloading the 2015 data yet. If I get this far, I'll tell you.
My last question about distributed training has been solved and deleted. But I found distributed training to be slower. Could you tell me, only on the 2020 dataset, the mAP and mIOU obtained by your model?

**Comment by satish1901** [comment]
Hello, 

sorry, I do not have mAP and mIOU number just for 2020 dataset.
