### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by yaoyuan10475** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#14]
Dear Author:
        When I download the data set, it appears "kex_exchange_identification: Connection closed by remote host". What is the reason for this? How can I solve it. Thanks!
![下载失败](https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/assets/74589851/23e80a58-2ac3-4ac0-893b-7bf45cb93902)

**Comment by Cigaftex** [comment]
Hello, may I ask how the problem was resolved？

**Comment by yaoyuan10475** [comment]
The problem has not been solved, but it should be that the IP address is requested too frequently. You should be able to solve it by changing your IP address.

**Comment by satish1901** [comment]
hello, 
the recent connection refuse was because, we setup this server using docker container, and recently we started the server and somehow the container did not come up with the server. This time the issue was on our side, please let me know if you face it again the future

**Comment by Cigaftex** [comment]
It works. Thanks a lot.
