### ISSUE TITLE
label conflict

### ISSUE THREAD

**Issue by yaoyuan10475** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#15]
Dear author:
Sorry for bothering you so many times.
I found that in the annotations_16171819.json file, image_id and patch_id have a lot of the same, but their patch_name is not the same. In the training_data16171819 folder, image_id plus patch_id represent the only sample. This will cause the problem of one sample corresponding to multiple labels.
for example:
There is only one ang20171024t215215_rdn_v2p12_img_tiles/ang20171024t215215_img_tiles_78_3.npy in rgb_tiles, rdata_tiles and mf_tiles, but there are two labels in annotations_16171819.json, both corresponding to the same image_id and patch_id. But which one is the label corresponding to ang20171024t215215_img_tiles_78_3.npy. Or have other understandings.

**Comment by satish1901** [comment]
Hello Yuan 

Appologies for the late response. 
Both the labels are correct. There are many cases, when a single tile has 2 methane plumes. Both of them are correct labels. 
I hope this clears the confusion. Please let me know if it helps

**Comment by yaoyuan10475** [comment]
Don't mention it.
I know what you mean. There are multiple methane plumes in one image. For example, the segmentation list contains multiple two-dimensional lists representing different methane plume. But a picture determined by image id and patch id has multiple segmentation in the annotations_16171819.json file. For example, the image id is ang20171024t215215 and the patch id is 78_3.
