### ISSUE TITLE
Sftp login needs password.

### ISSUE THREAD

**Issue by DevilHao666** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#17]
![N$9T%8 S(KHD~J 4W}U~$MO](https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/assets/92613748/6eaa9635-35b2-4bc2-b535-cbb73c3a4219)

**Comment by ICDX01** [comment]
Same issue.

**Comment by satish1901** [comment]
Hello, 
There is no password attached. 
please try again. I just verified it. 
OR
just hit spacebar on your keyboard as password and hit enter

Please let me know if you still face the issue.

**Comment by ICDX01** [comment]
It works. Thanks a lot.

**Comment by DevilHao666** [comment]
Hello, I interrupted while downloading the dataset and later accessed the download sub file again. Unable to access the download again today. May I ask if my IP address has been hacked due to too many visits, or other reasons. Thank you for your help.
![112233](https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/assets/92613748/84724aee-363d-41e2-a72c-902bcd82eaf4)

**Comment by satish1901** [comment]
Hello, 

Please try again now. It should be working. Sorry for the inconvenience.

Thank you
