### ISSUE TITLE
The saved weights for the trained models are not visible. 

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#18]
Hi. 
I understand the saved coefficients should be available or linked inside `methanemapper/exps/`, but they are not there. 
Could you share them or indicate a path do download ?

Thank you.

**Comment by satish1901** [comment]
Hello 
We are planning to commercialize the MethaneMapper. Apologies, we can not share the trained weights, we have made the code base and dataset available, you can use those to train the model yourself

Thank you
