### ISSUE TITLE
The SFTP channel (sftp -P 2022 anonymous@brain.ece.ucsb.edu) is currently unavailable !

### ISSUE THREAD

**Issue by Cigaftex** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#19]
During the course of our work, we encountered an issue acessing the data through the provided SFTP channel (sftp -P 2022 anonymous@brain.ece.ucsb.edu), which seems to be inaccessible at the moment.
![image](https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/assets/70827462/c66e891a-eba7-492f-9fcb-c50dd7f42a71)

Could you please advise if there's a way to restore our access to the data? Altematvely, if there's another pathway or method to access the infommation, we would greatly appreciate your guidance on how to proceed.

**Comment by connor11son** [comment]
We have resolved this issue - please let us know if you have any issues accessing the data in the future.

**Comment by satish1901** [comment]
I am closing this issue, Please open again if you face any problem!

**Comment by Cigaftex** [comment]
It works. Thanks a lot.
