### ISSUE TITLE
How to visualize the result by inputing an image

### ISSUE THREAD

**Issue by LiutonCannon** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#20]
Dear Author:
    I get the file checkpoint.pth after training, but I don't know how to visualize the result by inputing an image like that in the paper. Could you tell me about this. Thanks!
<img width="358" alt="e69a8c706f9e5a4e8362e2ab7273b26" src="https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/assets/66772944/ebc72dc9-57a2-4ead-90c5-c81130249f0e">

**Comment by xiaoayy** [comment]
Hello, I have also encountered the same problem that is bothering me. Could you please share your solution? Thank you very much.
