### ISSUE TITLE
About methane_signature.txt

### ISSUE THREAD

**Issue by Mohouwa** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#21]
Hello, may I ask how the file methane_signature.txt provided by you was calculated? The results I obtained using HITRAN's hapi calculation differ from yours. Here is my calculation script：

selectrange = select('CH4', Conditions=('between', 'nu', 376, 2500))
nu, coef = absorptionCoefficient_Voigt(selectrange, OmegaStep=5, HITRAN_units=False, Environment={'p': 1, 'T': 296.,'l':1000}, Diluent={'self': 0, 'air': 1 })
nu, transm = transmittanceSpectrum(nu, coef, Environment={'l': 1000, 'T': 296.})  

I calculated transm using this method and subtracted it from 1, but the results（bellow) differ significantly from the data you provided.

![d273dd5f0807701177b7841c39c7901](https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/assets/105279120/cbb81013-10b3-4a41-8170-d1e90bcf9e1e)

**Comment by satish1901** [comment]
Hello, 

Sincere apologies for so late response to your query. 
Here is the code I used to download the methane signature from HITRAN API

`        # Get abs coefficient and save to path download_dir
        band_name = f'CH4_{band}'
        fetch(band_name, 6, 1, self.wv_min, self.wv_max)
        band_wv, band_coef = absorptionCoefficient_Lorentz(SourceTables=band_name, HITRAN_units=False)
        band_wv, band_absorb = absorptionSpectrum(band_wv, band_coef)
        band_wv, band_trans = transmittanceSpectrum(band_wv, band_coef)
`

you can make minor changes to this code for downloading data from wavelength range 400-2500 nm
