### ISSUE TITLE
Which years of data are used for the results in Table 2?

### ISSUE THREAD

**Issue by yaoyuan10475** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#22]
Hello, dear author. 
Are the experimental results in Table 2 the data from 2015 to 2022? In the code you published, only data from 2020 or 2016-2019 is loaded. If I follow train's tutorial, I can only get results for 2020 or 2016-2019. Are the data from 2015, 2021, and 2022 not used in the paper?

**Comment by satish1901** [comment]
Hello, 
sincere apologies for such a late response!

The Table 2 in paper, the data is from 2015 and 2016-2021

the top section of the table titled "JPL-CH4-detection-v1.0 Dataset" is the 2015 dataset released by JPL

The bottom section of the table titled "MHS (Ours) Dataset" is the 2016-2021 dataset that we curated.
When you download the dataset using the sftp server, there are 2 download folders
1. public/training_data16171819
2. public/training_data2020

If you are not able to resolve the issue, please let me know.

**Comment by Gsl-m** [comment]
Hello, dear author.
But I still have a question. Where can I download the training_data2021?
