### ISSUE TITLE
MHS dataset

### ISSUE THREAD

**Issue by 1750585724** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#4]
How to download MHS dataset?

**Comment by satish1901** [comment]
Hello 

Sorry for the delay in data availability. I have released the MHS dataset download process along with a tutorial. 
Please follow that and let me know if you face any issue

Link : https://github.com/UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection/tree/main/mhs_dataset

Thank you,
