### ISSUE TITLE
SFTP server password

### ISSUE THREAD

**Issue by 1750585724** [UCSB-VRL/MethaneMapper-Spectral-Absorption-aware-Hyperspectral-Transformer-for-Methane-Detection#5]
When I connect to SFTP server using the following command, it prompts I need a password. What is the password?

**Comment by satish1901** [comment]
Actually there is no password. SFTP sometimes does that.
Just try again 
And if it ask for password again, just put space in password and enter or nothing and enter 

let me know if that works

**Comment by 1750585724** [comment]
Thank you! The problem has been solved.

**Comment by satish1901** [comment]
Thanks, I will update this information in README.md file  and close the issue.

**Comment by satish1901** [comment]
Hello, 
How long did it take for you to download the whole dataset and how much internet bandwidth you had? 
Just trying to get an estimate of the time!

**Comment by 1750585724** [comment]
Sorry, the dataset has not been downloaded yet within 24 hours.

**Comment by satish1901** [comment]
Thanks. Yes, it might take some time to download it. It took me 4 days to upload all on 1 gb connection
